stages:
  - publish

variables:
  PROJ_VERSION: v0.0.1
  TAG_LATEST: devops.oexpo.io/$PROJECT_NAME/$IMAGE_NAME:latest
  TAG_CURR: devops.oexpo.io/$PROJECT_NAME/$IMAGE_NAME:$PROJ_VERSION

publish-flutter:
  image: cirrusci/flutter:2.10.5
  stage: publish
  tags:
    - deployment
  before_script:
    - flutter pub get
  script:
    - flutter build web --dart-define=MAIN_SERVER_ADDRESS=$MAIN_SERVER_ADDRESS --dart-define=GOOGLE_SIGN_IN_CLIENT_ID=$GOOGLE_SIGN_IN_CLIENT_ID 
  only:
    - main
