stages:
  - build
  - deploy

variables:
  PROJ_VERSION: v0.0.1
  TAG_LATEST: devops.oexpo.io/$PROJECT_NAME/$IMAGE_NAME:latest
  TAG_CURR: devops.oexpo.io/$PROJECT_NAME/$IMAGE_NAME:$PROJ_VERSION

build:
  image: cirrusci/flutter:2.10.5
  stage: build
  tags:
    - deployment
  before_script:
    - flutter pub get
  script:
    - flutter build web --dart-define=MAIN_SERVER_ADDRESS=$MAIN_SERVER_ADDRESS --dart-define=GOOGLE_SIGN_IN_CLIENT_ID=$GOOGLE_SIGN_IN_CLIENT_ID 
  only:
    - main
  artifacts:
    paths:
      - build/web

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - echo "$AWS_VM_CER" >> peerreview.crt
    - chmod 400 peerreview.crt
    - ssh -i peerreview.crt -o StrictHostKeyChecking=no $AWS_VM "rm -rf /home/ubuntu/peer-review-build/dev/*"
    - ssh -i peerreview.crt -o StrictHostKeyChecking=no $AWS_VM "ls -lhta /home/ubuntu/peer-review-build/dev/"
    - scp -r -i peerreview.crt -o StrictHostKeyChecking=no build/web/* $AWS_VM:/home/ubuntu/peer-review-build/dev/
